import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'


export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 9</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='fondo__main'>
        <div className='contenedor__titulo'>
          <h1 className='titulo'>Ejercicio Clase 9</h1>
        </div>
      </main>
    </>
  )
}
